namespace pfm.Models
{
    public enum MCC
    {/*
        Telecommunication service including local and long distance calls credit card calls calls through use of magneticstrip reading telephones and fax services	=	4814
VisaPhone	=	4815
Telegraph services	=	4821
Money Orders - Wire Transfer	=	4829
Cable and other pay television (previously Cable Services)	=	4899
Electric Gas Sanitary and Water Utilities	=	4900
Motor vehicle supplies and new parts	=	5013
Office and Commercial Furniture	=	5021
Construction Materials Not Elsewhere Classified	=	5039
Office Photographic Photocopy and Microfilm Equipment	=	5044
Computers Computer Peripheral Equipment Software	=	5045
Commercial Equipment Not Elsewhere Classified	=	5046
Medical Dental Ophthalmic Hospital Equipment and Supplies	=	5047
Metal Service Centers and Offices	=	5051
Electrical Parts and Equipment	=	5065
Hardware Equipment and Supplies	=	5072
Plumbing and Heating Equipment and Supplies	=	5074
Industrial Supplies Not Elsewhere Classified	=	5085
Precious Stones and Metals Watches and Jewelry	=	5094
Durable Goods Not Elsewhere Classified	=	5099
Stationery Office Supplies Printing and Writing Paper	=	5111
Drugs Drug Proprietors and Druggist's Sundries	=	5122
Piece Goods Notions and Other Dry Goods	=	5131
Men's Women's and Children's Uniforms and Commercial Clothing	=	5137
Commercial Footwear	=	5139
Chemicals and Allied Products Not Elsewhere Classified	=	5169
Petroleum and Petroleum Products	=	5172
Books Periodicals and Newspapers	=	5192
Florists- Supplies Nursery Stock and Flowers	=	5193
Paints Varnishes and Supplies	=	5198
Non-durable Goods Not Elsewhere Classified	=	5199
Home Supply Warehouse Stores	=	5200
Lumber and Building Materials Stores	=	5211
Glass Stores	=	5231
Paint and Wallpaper Stores	=	5231
Wallpaper Stores	=	5231
Hardware Stores	=	5251
Nurseries - Lawn and Garden Supply Store	=	5261
Mobile Home Dealers	=	5271
Wholesale Clubs	=	5300
Duty Free Store	=	5309
Discount Stores	=	5310
Department Stores	=	5311
Variety Stores	=	5331
Misc. General Merchandise	=	5399
Grocery Stores	=	5411
Supermarkets	=	5411
Freezer and Locker Meat Provisioners	=	5422
Meat Provisioners - Freezer and Locker	=	5422
Candy Stores	=	5441
Confectionery Stores	=	5441
Nut Stores	=	5441
Dairy Products Stores	=	5451
Bakeries	=	5462
Misc. Food Stores - Convenience Stores and Specialty Markets	=	5499
Car and Truck Dealers (New and Used) Sales Service Repairs Parts and Leasing	=	5511
Automobile and Truck Dealers (Used Only)	=	5521
Automobile Supply Stores	=	5531
Automotive Tire Stores	=	5532
Automotive Parts Accessories Stores	=	5533
Service Stations ( with or without ancillary services)	=	5541
Automated Fuel Dispensers	=	5542
Boat Dealers	=	5551
Recreational and Utility Trailers Camp Dealers	=	5561
Motorcycle Dealers	=	5571
Motor Home Dealers	=	5592
Snowmobile Dealers	=	5598
Men's and Boy's Clothing and Accessories Stores	=	5611
Women's Ready - to - Wear Stores	=	5621
Women's Accessory and Specialty Shops	=	5631
Children's and Infant's Wear Stores	=	5641
Family Clothing Stores	=	5651
Sports Apparel Riding Apparel Stores	=	5655
Shoe Stores	=	5661
Furriers and Fur Shops	=	5681
Men's and Women's Clothing Stores	=	5691
Tailors Seamstress Mending and Alterations	=	5697
Wig and Toupee Stores	=	5698
Miscellaneous Apparel and Accessory Shops	=	5699
Furniture Home Furnishings and Equipment Stores Except Appliances	=	5712
Floor Covering Stores	=	5713
Drapery Window Covering and Upholstery Stores	=	5714
Fireplace Fireplace Screens and Accessories Stores	=	5718
Miscellaneous Home Furnishing Specialty Stores	=	5719
Household Appliance Stores	=	5722
Electronic Sales	=	5732
Music Stores Musical Instruments Piano Sheet Music	=	5733
Computer Software Stores	=	5734
Record Shops	=	5735
Caterers	=	5811
Eating places and Restaurants	=	5812
Drinking Places (Alcoholic Beverages) Bars Taverns Cocktail lounges Nightclubs and Discotheques	=	5813
Fast Food Restaurants	=	5814
Drug Stores and Pharmacies	=	5912
Package Stores - Beer Wine and Liquor	=	5921
Used Merchandise and Secondhand Stores	=	5931
Antique Shops - Sales Repairs and Restoration Services	=	5832
Pawn Shops and Salvage Yards	=	5933
Wrecking and Salvage Yards	=	5935
Antique Reproductions	=	5937
Bicycle Shops - Sales and Service	=	5940
Sporting Goods Stores	=	5941
Book Stores	=	5942
Stationery Stores Office and School Supply Stores	=	5943
Watch Clock Jewelry and Silverware Stores	=	5944
Hobby Toy and Game Shops	=	5945
Camera and Photographic Supply Stores	=	5946
Card Shops Gift Novelty and Souvenir Shops	=	5947
Leather Foods Stores	=	5948
Sewing Needle Fabric and Price Goods Stores	=	5949
Glassware/Crystal Stores	=	5950
Direct Marketing - Insurance Service	=	5960
Mail Order Houses Including Catalog Order Stores Book/Record Clubs (No longer permitted for .S. original presentments)	=	5961
Direct Marketing - Travel Related Arrangements Services	=	5962
Door - to - Door Sales	=	5963
Direct Marketing - Catalog Merchant	=	5964
Direct Marketing - Catalog and Catalog and Retail Merchant Direct Marketing - Outbound Telemarketing Merchant	=	5965
Direct Marketing -Inbound Teleservices Merchant	=	5967
Direct Marketing - Continuity/Subscription Merchant	=	5968
Direct Marketing - Not Elsewhere Classified	=	5969
Artist's Supply and Craft Shops	=	5970
Art Dealers and Galleries	=	5971
Stamp and Coin Stores - Philatelic and Numismatic Supplies	=	5972
Religious Goods Stores	=	5973
Hearing Aids - Sales Service and Supply Stores	=	5975
Orthopedic Goods Prosthetic Devices	=	5976
Cosmetic Stores	=	5977
Typewriter Stores - Sales Rental Service	=	5978
Fuel - Fuel Oil Wood Coal Liquefied Petroleum	=	5983
Florists	=	5992
Cigar Stores and Stands	=	5993
News Dealers and Newsstands	=	5994
Pet Shops Pet Foods and Supplies Stores	=	5995
Swimming Pools - Sales Service and Supplies	=	5996
Electric Razor Stores - Sales and Service	=	5997
Tent and Awning Shops	=	5998
Miscellaneous and Specialty Retail Stores	=	5999
Financial Institutions - Manual Cash Disbursements	=	6010
Financial Institutions - Manual Cash Disbursements	=	6011
Financial Institutions - Merchandise and Services	=	6012
Non - Financial Institutions - Foreign Currency Money Orders (not wire transfer) and Travelers Cheques	=	6051
Security Brokers/Dealers	=	6211
Insurance Sales Underwriting and Premiums	=	6300
Insurance Premiums (no longer valid for first presentment work)	=	6381
Insurance Not Elsewhere Classified ( no longer valid for first presentment work)	=	6399
Lodging - Hotels Motels Resorts Central Reservation Services (not elsewhere classified)	=	7011
Timeshares	=	7012
Sporting and Recreational Camps	=	7032
Trailer Parks and Camp Grounds	=	7033
Laundry Cleaning and Garment Services	=	7210
Laundry - Family and Commercial	=	7211
Dry Cleaners	=	7216
Carpet and Upholstery Cleaning	=	7217
Photographic Studios	=	7221
Barber and Beauty Shops	=	7230
Shop Repair Shops and Shoe Shine Parlors and Hat Cleaning Shops	=	7251
Funeral Service and Crematories	=	7261
Dating and Escort Services	=	7273
Tax Preparation Service	=	7276
Counseling Service - Debt Marriage Personal	=	7277
Buying/Shopping Services Clubs	=	7278
Clothing Rental - Costumes Formal Wear Uniforms	=	7296
Massage Parlors	=	7297
Health and Beauty Shops	=	7298
Miscellaneous Personal Services ( not elsewhere classifies)	=	7299
Advertising Services	=	7311
Consumer Credit Reporting Agencies	=	7321
Blueprinting and Photocopying Services	=	7332
Commercial Photography Art and Graphics	=	7333
Quick Copy Reproduction and Blueprinting Services	=	7338
Stenographic and Secretarial Support Services	=	7339
Disinfecting Services	=	7342
Exterminating and Disinfecting Services	=	7342
Cleaning and Maintenance Janitorial Services	=	7349
Employment Agencies Temporary Help Services	=	7361
Computer Programming Integrated Systems Design and Data Processing Services	=	7372
Information Retrieval Services	=	7375
Computer Maintenance and Repair Services Not Elsewhere Classified	=	7379
Management Consulting and Public Relations Services	=	7392
Protective and Security Services - Including Armored Cars and Guard Dogs	=	7393
Equipment Rental and Leasing Services Tool Rental Furniture Rental and Appliance Rental	=	7394
Photofinishing Laboratories Photo Developing	=	7395
Business Services Not Elsewhere Classified	=	7399
Car Rental Companies ( Not Listed Below)	=	7512
Truck and Utility Trailer Rentals	=	7513
Motor Home and Recreational Vehicle Rentals	=	7519
Automobile Parking Lots and Garages	=	7523
Automotive Body Repair Shops	=	7531
Tire Re - treading and Repair Shops	=	7534
Paint Shops - Automotive	=	7535
Automotive Service Shops	=	7538
Car Washes	=	7542
Towing Services	=	7549
Radio Repair Shops	=	7622
Air Conditioning and Refrigeration Repair Shops	=	7623
Electrical And Small Appliance Repair Shops	=	7629
Watch Clock and Jewelry Repair	=	7631
Furniture Furniture Repair and Furniture Refinishing	=	7641
Welding Repair	=	7692
Repair Shops and Related Services - Miscellaneous	=	7699
Motion Pictures and Video Tape Production and Distribution	=	7829
Motion Picture Theaters	=	7832
Video Tape Rental Stores	=	7841
Dance Halls Studios and Schools	=	7911
Theatrical Producers (Except Motion Pictures) Ticket Agencies	=	7922
Bands. Orchestras and Miscellaneous Entertainers (Not Elsewhere Classified)	=	7929
Billiard and Pool Establishments	=	7932
Bowling Alleys	=	7933
Commercial Sports Athletic Fields Professional Sport Clubs and Sport Promoters	=	7941
Tourist Attractions and Exhibits	=	7991
Golf Courses - Public	=	7992
Video Amusement Game Supplies	=	7993
Video Game Arcades/Establishments	=	7994
Betting (including Lottery Tickets Casino Gaming Chips Off - track Betting and Wagers)	=	7995
Amusement Parks Carnivals Circuses Fortune Tellers	=	7996
Membership Clubs (Sports Recreation Athletic) Country Clubs AndPrivateGolfCourses = 7997,
        AquariumsSeaAquariumsDolphinariums = 7998,
        RecreationServicesNotElsewhereClassified = 7999,
        DoctorsAndPhysiciansNotElsewhereClassified = 8011,
        DentistsAndOrthodontists = 8021,
        Osteopaths = 8031,
        Chiropractors = 8041,
        OptometristsAndOphthalmologists = 8042,
        OpticiansOpticiansGoodsAndEyeglasses = 8043,
        OpticiansOpticalGoodsAndEyeglassesNoLongerValidForFirstPresentments = 8044,
        PodiatristsAndChiropodists = 8049,
        NursingAndPersonalCareFacilities = 8050,
        Hospitals = 8062,
        MedicalAndDentalLaboratories = 8071,
        MedicalServicesAndHealthPractitionersNotElsewhereClassified = 8099,
        LegalServicesAndAttorneys = 8111,
        ElementaryAndSecondarySchools = 8211,
        CollegesJuniorCollegesUniversitiesAndProfessionalSchools = 8220,
        CorrespondenceSchools = 8241,
        BusinessAndSecretarialSchools = 8244,
        VocationalSchoolsAndTradeSchools = 8249,
        SchoolsAndEducationalServicesNotElsewhereClassified = 8299,
        ChildCareServices = 8351,
        CharitableAndSocialServiceOrganizations	= 8398,
        CivicFraternalAndSocialAssociations	= 8641,
        PoliticalOrganizations = 8651,
        ReligiousOrganizations = 8661,
        AutomobileAssociations = 8675,
        MembershipOrganizationsNotElsewhereClassified = 8699,
        TestingLaboratoriesNonMedical = 8734,
        ArchitecturalEngineeringAndSurveyingServices = 8911,
        AccountingAuditingAndBookkeepingServices = 8931,
        ProfessionalServicesNotElsewhereDefined = 8999,
        CourtCostsIncludingAlimonyAndChildSupport = 9211,
        Fines = 9222,
        BailAndBondPayments = 9223,
        TaxPayments = 9311,
        GovernmentServicesNotElsewhereClassified = 9399,
        PostalServicesGovernmentOnly = 9402,
        IntraGovernmentTransactions	= 9405,
        AutomatedReferralServiceForVisaOnly = 9700,
        VisaCredentialServiceForVisaOnly = 9701,
        GCASEmergencyServicesForVisaOnly = 9702,
        IntraCompanyPurchasesForVisaOnly = 9950,*/

    }
}